# Generated by Django 4.2.7 on 2025-08-18 09:03

import api.models.chat
import api.models.profile
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="Phone number must be exactly 10 digits (e.g., 0123456789)",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("student", "Student"), ("tutor", "Tutor")],
                        max_length=10,
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("school", models.CharField(blank=True, max_length=200)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("1", "Lớp 1"),
                            ("2", "Lớp 2"),
                            ("3", "Lớp 3"),
                            ("4", "Lớp 4"),
                            ("5", "Lớp 5"),
                            ("6", "Lớp 6"),
                            ("7", "Lớp 7"),
                            ("8", "Lớp 8"),
                            ("9", "Lớp 9"),
                            ("10", "Lớp 10"),
                            ("11", "Lớp 11"),
                            ("12", "Lớp 12"),
                            ("university", "Đại học"),
                        ],
                        max_length=20,
                    ),
                ),
                ("learning_goals", models.JSONField(blank=True, default=list)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hanoi", "Hà Nội"),
                            ("hochiminh", "TP. Hồ Chí Minh"),
                            ("danang", "Đà Nẵng"),
                            ("haiphong", "Hải Phòng"),
                            ("cantho", "Cần Thơ"),
                            ("binhduong", "Bình Dương"),
                            ("dongnai", "Đồng Nai"),
                            ("baivungtau", "Bà Rịa - Vũng Tàu"),
                            ("quangninh", "Quảng Ninh"),
                            ("thainguyen", "Thái Nguyên"),
                            ("vinhphuc", "Vĩnh Phúc"),
                            ("bacninh", "Bắc Ninh"),
                            ("haiduong", "Hải Dương"),
                            ("hungyen", "Hưng Yên"),
                            ("namdinh", "Nam Định"),
                            ("thaibinh", "Thái Bình"),
                            ("ninhbinh", "Ninh Bình"),
                            ("thanhhoa", "Thanh Hóa"),
                            ("nghean", "Nghệ An"),
                            ("hatinh", "Hà Tĩnh"),
                            ("quangbinh", "Quảng Bình"),
                            ("quangtri", "Quảng Trị"),
                            ("thuathienhue", "Thừa Thiên Huế"),
                            ("quangnam", "Quảng Nam"),
                            ("quangngai", "Quảng Ngãi"),
                            ("binhdinh", "Bình Định"),
                            ("phuyen", "Phú Yên"),
                            ("khanhhoa", "Khánh Hòa"),
                            ("ninhthuan", "Ninh Thuận"),
                            ("binhthuan", "Bình Thuận"),
                            ("lamdong", "Lâm Đồng"),
                            ("tayninh", "Tây Ninh"),
                            ("binhphuoc", "Bình Phước"),
                            ("longan", "Long An"),
                            ("tiengiang", "Tiền Giang"),
                            ("bentre", "Bến Tre"),
                            ("travinh", "Trà Vinh"),
                            ("vinhlong", "Vĩnh Long"),
                            ("dongthap", "Đồng Tháp"),
                            ("angiang", "An Giang"),
                            ("kiengiang", "Kiên Giang"),
                            ("camau", "Cà Mau"),
                            ("baclieu", "Bạc Liêu"),
                            ("soctrang", "Sóc Trăng"),
                            ("other", "Tỉnh/Thành phố khác"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, upload_to=api.models.profile.user_profile_path
                    ),
                ),
            ],
            options={
                "db_table": "student_profiles",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TutorAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TutorProfile",
            fields=[
                ("education", models.CharField(blank=True, max_length=200)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hanoi", "Hà Nội"),
                            ("hochiminh", "TP. Hồ Chí Minh"),
                            ("danang", "Đà Nẵng"),
                            ("haiphong", "Hải Phòng"),
                            ("cantho", "Cần Thơ"),
                            ("binhduong", "Bình Dương"),
                            ("dongnai", "Đồng Nai"),
                            ("baivungtau", "Bà Rịa - Vũng Tàu"),
                            ("quangninh", "Quảng Ninh"),
                            ("thainguyen", "Thái Nguyên"),
                            ("vinhphuc", "Vĩnh Phúc"),
                            ("bacninh", "Bắc Ninh"),
                            ("haiduong", "Hải Dương"),
                            ("hungyen", "Hưng Yên"),
                            ("namdinh", "Nam Định"),
                            ("thaibinh", "Thái Bình"),
                            ("ninhbinh", "Ninh Bình"),
                            ("thanhhoa", "Thanh Hóa"),
                            ("nghean", "Nghệ An"),
                            ("hatinh", "Hà Tĩnh"),
                            ("quangbinh", "Quảng Bình"),
                            ("quangtri", "Quảng Trị"),
                            ("thuathienhue", "Thừa Thiên Huế"),
                            ("quangnam", "Quảng Nam"),
                            ("quangngai", "Quảng Ngãi"),
                            ("binhdinh", "Bình Định"),
                            ("phuyen", "Phú Yên"),
                            ("khanhhoa", "Khánh Hòa"),
                            ("ninhthuan", "Ninh Thuận"),
                            ("binhthuan", "Bình Thuận"),
                            ("lamdong", "Lâm Đồng"),
                            ("tayninh", "Tây Ninh"),
                            ("binhphuoc", "Bình Phước"),
                            ("longan", "Long An"),
                            ("tiengiang", "Tiền Giang"),
                            ("bentre", "Bến Tre"),
                            ("travinh", "Trà Vinh"),
                            ("vinhlong", "Vĩnh Long"),
                            ("dongthap", "Đồng Tháp"),
                            ("angiang", "An Giang"),
                            ("kiengiang", "Kiên Giang"),
                            ("camau", "Cà Mau"),
                            ("baclieu", "Bạc Liêu"),
                            ("soctrang", "Sóc Trăng"),
                            ("other", "Tỉnh/Thành phố khác"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "rating_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.IntegerField(default=0)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, upload_to=api.models.profile.user_profile_path
                    ),
                ),
                ("availability", models.JSONField(blank=True, default=dict)),
                (
                    "price_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "achievements",
                    models.ManyToManyField(
                        blank=True, related_name="tutors", to="api.tutorachievement"
                    ),
                ),
                (
                    "class_levels",
                    models.ManyToManyField(
                        blank=True, related_name="tutors", to="api.classlevel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewed_tutors",
                        to="api.studentprofile",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="api.tutorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("basic", "Cơ Bản"), ("advanced", "Nâng Cao")],
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.subject"
                    ),
                ),
                (
                    "tutor_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_subjects",
                        to="api.tutorprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("tutor_profile", "subject", "level")},
            },
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="subjects",
            field=models.ManyToManyField(through="api.TutorSubject", to="api.subject"),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TutorLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_profile_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_tutors",
                        to="api.studentprofile",
                        to_field="uuid",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="api.tutorprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tutorachievement",
            name="tutor_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutor_achievements",
                to="api.tutorprofile",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="preferred_subjects",
            field=models.ManyToManyField(blank=True, to="api.subject"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to="api.studentprofile",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to="api.tutorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("file", "File"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "file_attachment",
                    models.FileField(
                        blank=True, upload_to=api.models.chat.chat_file_path
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.chatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatroom",
            name="student",
            field=models.ForeignKey(
                db_column="student_profile_uuid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="api.studentprofile",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="api.tutorprofile",
            ),
        ),
        migrations.CreateModel(
            name="TutorSave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_profile_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_tutors",
                        to="api.studentprofile",
                        to_field="uuid",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="api.tutorprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "tutor")},
            },
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["price_min"], name="api_tutorpr_price_m_0c7d70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["price_max"], name="api_tutorpr_price_m_1b5aab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["location"], name="api_tutorpr_locatio_83dc35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["rating_average"], name="api_tutorpr_rating__684a52_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tutorlike",
            unique_together={("student", "tutor")},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("student", "tutor")},
        ),
        migrations.AlterUniqueTogether(
            name="chatroom",
            unique_together={("student", "tutor")},
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["user_type", "created_at"],
                name="api_customu_user_ty_ed429e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["is_online"], name="api_customu_is_onli_c4543c_idx"
            ),
        ),
    ]
