# Generated by Django 4.2.7 on 2025-07-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorprofile",
            name="top_achievements",
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="achievements",
            field=models.JSONField(
                blank=True, default=list, help_text="Achievements for quick display"
            ),
        ),
    ]
