# Generated by Django 4.2.7 on 2025-08-19 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message="Phone number must be 8 or 10 digits (e.g., 91234567 or 0123456789)",
                        regex="^(\\d{8}|\\d{10})$",
                    )
                ],
            ),
        ),
    ]
