# Generated by Django 4.2.7 on 2025-10-29 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="wallet_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True, default=uuid.uuid4, max_length=150, null=True
            ),
        ),
    ]
