# Generated by Django 4.2.7 on 2025-07-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_achievement_achievement_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[("basic", "Cơ Bản"), ("advanced", "Nâng Cao")],
                        max_length=20,
                    ),
                ),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="tutorprofile",
            name="tutor_profi_hourly__205d01_idx",
        ),
        migrations.AlterUniqueTogether(
            name="tutorsubject",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="experience_years",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="hourly_rate",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="major",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="university",
        ),
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(
                choices=[
                    ("math", "Toán"),
                    ("english", "Tiếng Anh"),
                    ("physics", "Vật Lý"),
                    ("chemistry", "Hóa Học"),
                    ("biology", "Sinh Học"),
                    ("literature", "Ngữ Văn"),
                    ("history", "Lịch Sử"),
                    ("geography", "Địa Lý"),
                ],
                default="temp",
                max_length=20,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="education",
            field=models.CharField(
                default="uni not updated",
                help_text="University and major combined",
                max_length=400,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="grade_levels",
            field=models.JSONField(
                default=list, help_text="List of grade levels: elementary, middle, high"
            ),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="max_hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="min_hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="teaches_offline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="teaches_online",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="top_achievements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Top 3 achievements for profile display",
            ),
        ),
        migrations.AlterField(
            model_name="tutorsubject",
            name="proficiency_level",
            field=models.CharField(
                choices=[("basic", "Cơ Bản"), ("advanced", "Nâng Cao")], max_length=20
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tutorsubject",
            unique_together={("tutor", "subject", "proficiency_level")},
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["min_hourly_rate"], name="tutor_profi_min_hou_feed31_idx"
            ),
        ),
        migrations.AddField(
            model_name="tutorpricing",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.subject"
            ),
        ),
        migrations.AddField(
            model_name="tutorpricing",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_entries",
                to="api.tutorprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tutorpricing",
            unique_together={("tutor", "subject", "proficiency_level")},
        ),
    ]
