# Generated by Django 4.2.7 on 2025-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_tutorprofile_top_achievements_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutorprofile",
            old_name="major",
            new_name="education",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="experience_years",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="university",
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="class_levels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="price_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="price_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="prices",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="subjects",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="achievements",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
