# Generated by Django 4.2.7 on 2025-07-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_tutorpricing_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("basic", "Cơ bản"), ("advanced", "Nâng cao")],
                        max_length=20,
                    ),
                ),
                ("price", models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="tutorpricing",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tutorpricing",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="tutorpricing",
            name="tutor",
        ),
        migrations.RemoveIndex(
            model_name="tutorprofile",
            name="tutor_profi_min_hou_feed31_idx",
        ),
        migrations.AlterUniqueTogether(
            name="tutorsubject",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="subject",
            name="code",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="grade_levels",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="max_hourly_rate",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="min_hourly_rate",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="teaches_offline",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="teaches_online",
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="teaching_classes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tutorsubject",
            name="level",
            field=models.CharField(
                choices=[("basic", "Cơ bản"), ("advanced", "Nâng cao")],
                default="not-updated",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="education",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="top_achievements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Top 2-3 achievements for quick display",
            ),
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["hourly_rate"], name="tutor_profi_hourly__205d01_idx"
            ),
        ),
        migrations.DeleteModel(
            name="TutorPricing",
        ),
        migrations.AddField(
            model_name="tutorprice",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.subject"
            ),
        ),
        migrations.AddField(
            model_name="tutorprice",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="api.tutorprofile",
            ),
        ),
        migrations.RemoveField(
            model_name="tutorsubject",
            name="proficiency_level",
        ),
        migrations.AlterUniqueTogether(
            name="tutorprice",
            unique_together={("tutor", "subject", "level")},
        ),
    ]
