# Generated by Django 4.2.7 on 2025-11-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_customuser_wallet_balance_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="preferences",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
