# Generated by Django 4.2.7 on 2025-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_major_tutorprofile_education_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tutorprofile",
            name="tutor_profi_hourly__205d01_idx",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="hourly_rate",
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["price_min"], name="tutor_profi_price_m_700030_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["price_max"], name="tutor_profi_price_m_9eea96_idx"
            ),
        ),
    ]
