# Generated by Django 4.2.7 on 2025-07-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_tutorprice_alter_tutorpricing_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutorprofile",
            old_name="education",
            new_name="major",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="teaching_classes",
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="experience_years",
            field=models.CharField(
                choices=[
                    ("0-1", "0-1 năm"),
                    ("1-3", "1-3 năm"),
                    ("3-5", "3-5 năm"),
                    ("5+", "Trên 5 năm"),
                ],
                default="not-updated",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="university",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tutorsubject",
            name="proficiency_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Cơ bản"),
                    ("intermediate", "Trung bình"),
                    ("advanced", "Nâng cao"),
                    ("expert", "Chuyên gia"),
                ],
                default="not-updated",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="tutorsubject",
            unique_together={("tutor", "subject")},
        ),
        migrations.DeleteModel(
            name="TutorPrice",
        ),
        migrations.RemoveField(
            model_name="tutorsubject",
            name="level",
        ),
    ]
