# Generated by Django 4.2.7 on 2025-07-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_tutorprofile_tutor_profi_hourly__205d01_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TutorAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name="tutorsubject",
            old_name="tutor",
            new_name="tutor_profile",
        ),
        migrations.AlterUniqueTogether(
            name="tutorsubject",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="subject",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="prices",
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tutorsubject",
            name="level",
            field=models.CharField(
                choices=[("basic", "Cơ Bản"), ("advanced", "Nâng Cao")],
                default="un-updated level",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tutorsubject",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.00, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hanoi", "Hà Nội"),
                    ("hochiminh", "TP. Hồ Chí Minh"),
                    ("danang", "Đà Nẵng"),
                    ("haiphong", "Hải Phòng"),
                    ("cantho", "Cần Thơ"),
                    ("binhduong", "Bình Dương"),
                    ("dongnai", "Đồng Nai"),
                    ("baivungtau", "Bà Rịa - Vũng Tàu"),
                    ("quangninh", "Quảng Ninh"),
                    ("thainguyen", "Thái Nguyên"),
                    ("vinhphuc", "Vĩnh Phúc"),
                    ("bacninh", "Bắc Ninh"),
                    ("haiduong", "Hải Dương"),
                    ("hungyen", "Hưng Yên"),
                    ("namdinh", "Nam Định"),
                    ("thaibinh", "Thái Bình"),
                    ("ninhbinh", "Ninh Bình"),
                    ("thanhhoa", "Thanh Hóa"),
                    ("nghean", "Nghệ An"),
                    ("hatinh", "Hà Tĩnh"),
                    ("quangbinh", "Quảng Bình"),
                    ("quangtri", "Quảng Trị"),
                    ("thuathienhue", "Thừa Thiên Huế"),
                    ("quangnam", "Quảng Nam"),
                    ("quangngai", "Quảng Ngãi"),
                    ("binhdinh", "Bình Định"),
                    ("phuyen", "Phú Yên"),
                    ("khanhhoa", "Khánh Hòa"),
                    ("ninhthuan", "Ninh Thuận"),
                    ("binhthuan", "Bình Thuận"),
                    ("lamdong", "Lâm Đồng"),
                    ("tayninh", "Tây Ninh"),
                    ("binhphuoc", "Bình Phước"),
                    ("longan", "Long An"),
                    ("tiengiang", "Tiền Giang"),
                    ("bentre", "Bến Tre"),
                    ("travinh", "Trà Vinh"),
                    ("vinhlong", "Vĩnh Long"),
                    ("dongthap", "Đồng Tháp"),
                    ("angiang", "An Giang"),
                    ("kiengiang", "Kiên Giang"),
                    ("camau", "Cà Mau"),
                    ("baclieu", "Bạc Liêu"),
                    ("soctrang", "Sóc Trăng"),
                    ("other", "Tỉnh/Thành phố khác"),
                ],
                max_length=50,
            ),
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="achievements",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="class_levels",
        ),
        migrations.AlterField(
            model_name="tutorprofile",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hanoi", "Hà Nội"),
                    ("hochiminh", "TP. Hồ Chí Minh"),
                    ("danang", "Đà Nẵng"),
                    ("haiphong", "Hải Phòng"),
                    ("cantho", "Cần Thơ"),
                    ("binhduong", "Bình Dương"),
                    ("dongnai", "Đồng Nai"),
                    ("baivungtau", "Bà Rịa - Vũng Tàu"),
                    ("quangninh", "Quảng Ninh"),
                    ("thainguyen", "Thái Nguyên"),
                    ("vinhphuc", "Vĩnh Phúc"),
                    ("bacninh", "Bắc Ninh"),
                    ("haiduong", "Hải Dương"),
                    ("hungyen", "Hưng Yên"),
                    ("namdinh", "Nam Định"),
                    ("thaibinh", "Thái Bình"),
                    ("ninhbinh", "Ninh Bình"),
                    ("thanhhoa", "Thanh Hóa"),
                    ("nghean", "Nghệ An"),
                    ("hatinh", "Hà Tĩnh"),
                    ("quangbinh", "Quảng Bình"),
                    ("quangtri", "Quảng Trị"),
                    ("thuathienhue", "Thừa Thiên Huế"),
                    ("quangnam", "Quảng Nam"),
                    ("quangngai", "Quảng Ngãi"),
                    ("binhdinh", "Bình Định"),
                    ("phuyen", "Phú Yên"),
                    ("khanhhoa", "Khánh Hòa"),
                    ("ninhthuan", "Ninh Thuận"),
                    ("binhthuan", "Bình Thuận"),
                    ("lamdong", "Lâm Đồng"),
                    ("tayninh", "Tây Ninh"),
                    ("binhphuoc", "Bình Phước"),
                    ("longan", "Long An"),
                    ("tiengiang", "Tiền Giang"),
                    ("bentre", "Bến Tre"),
                    ("travinh", "Trà Vinh"),
                    ("vinhlong", "Vĩnh Long"),
                    ("dongthap", "Đồng Tháp"),
                    ("angiang", "An Giang"),
                    ("kiengiang", "Kiên Giang"),
                    ("camau", "Cà Mau"),
                    ("baclieu", "Bạc Liêu"),
                    ("soctrang", "Sóc Trăng"),
                    ("other", "Tỉnh/Thành phố khác"),
                ],
                max_length=50,
            ),
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="subjects",
        ),
        migrations.AlterUniqueTogether(
            name="tutorsubject",
            unique_together={("tutor_profile", "subject", "level")},
        ),
        migrations.RemoveField(
            model_name="tutorsubject",
            name="proficiency_level",
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="achievements",
            field=models.ManyToManyField(
                blank=True, related_name="tutors", to="api.tutorachievement"
            ),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="class_levels",
            field=models.ManyToManyField(
                blank=True, related_name="tutors", to="api.classlevel"
            ),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="subjects",
            field=models.ManyToManyField(through="api.TutorSubject", to="api.subject"),
        ),
    ]
