# Generated by Django 4.2.7 on 2025-07-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_classlevel_tutorachievement_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customuser",
            new_name="api_customu_user_ty_ed429e_idx",
            old_name="auth_user_user_ty_92c122_idx",
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="api_customu_is_onli_c4543c_idx",
            old_name="auth_user_is_onli_e080a7_idx",
        ),
        migrations.RemoveField(
            model_name="tutorachievement",
            name="description",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Optional. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table=None,
        ),
    ]
