# Generated by Django 4.2.7 on 2025-07-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_optional_username"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tutorprofile",
            new_name="api_tutorpr_price_m_0c7d70_idx",
            old_name="tutor_profi_price_m_700030_idx",
        ),
        migrations.RenameIndex(
            model_name="tutorprofile",
            new_name="api_tutorpr_price_m_1b5aab_idx",
            old_name="tutor_profi_price_m_9eea96_idx",
        ),
        migrations.RenameIndex(
            model_name="tutorprofile",
            new_name="api_tutorpr_locatio_83dc35_idx",
            old_name="tutor_profi_locatio_b2ad69_idx",
        ),
        migrations.RenameIndex(
            model_name="tutorprofile",
            new_name="api_tutorpr_rating__684a52_idx",
            old_name="tutor_profi_rating__54087e_idx",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="achievements",
        ),
        migrations.AddField(
            model_name="tutorachievement",
            name="tutor_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="api.tutorprofile",
            ),
        ),
        migrations.AlterModelTable(
            name="tutorprofile",
            table=None,
        ),
    ]
