# Generated by Django 4.2.7 on 2025-12-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_admin_subject", models.BooleanField(default=False)),
            ],
        ),
    ]
