# Generated by Django 4.2.7 on 2025-12-15 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="student",
            field=models.ForeignKey(
                db_column="student_profile_uuid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="profiles.studentprofile",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="profiles.tutorprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatroom",
            unique_together={("student", "tutor")},
        ),
    ]
