# Generated by Django 4.2.7 on 2025-12-14 03:22

from django.db import migrations, models
import django.db.models.deletion
import profiles.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("school", models.CharField(blank=True, max_length=200)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("1", "Lớp 1"),
                            ("2", "Lớp 2"),
                            ("3", "Lớp 3"),
                            ("4", "Lớp 4"),
                            ("5", "Lớp 5"),
                            ("6", "Lớp 6"),
                            ("7", "Lớp 7"),
                            ("8", "Lớp 8"),
                            ("9", "Lớp 9"),
                            ("10", "Lớp 10"),
                            ("11", "Lớp 11"),
                            ("12", "Lớp 12"),
                            ("university", "Đại học"),
                        ],
                        max_length=20,
                    ),
                ),
                ("learning_goals", models.JSONField(blank=True, default=list)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hanoi", "Hà Nội"),
                            ("hochiminh", "TP. Hồ Chí Minh"),
                            ("danang", "Đà Nẵng"),
                            ("haiphong", "Hải Phòng"),
                            ("cantho", "Cần Thơ"),
                            ("binhduong", "Bình Dương"),
                            ("dongnai", "Đồng Nai"),
                            ("baivungtau", "Bà Rịa - Vũng Tàu"),
                            ("quangninh", "Quảng Ninh"),
                            ("thainguyen", "Thái Nguyên"),
                            ("vinhphuc", "Vĩnh Phúc"),
                            ("bacninh", "Bắc Ninh"),
                            ("haiduong", "Hải Dương"),
                            ("hungyen", "Hưng Yên"),
                            ("namdinh", "Nam Định"),
                            ("thaibinh", "Thái Bình"),
                            ("ninhbinh", "Ninh Bình"),
                            ("thanhhoa", "Thanh Hóa"),
                            ("nghean", "Nghệ An"),
                            ("hatinh", "Hà Tĩnh"),
                            ("quangbinh", "Quảng Bình"),
                            ("quangtri", "Quảng Trị"),
                            ("thuathienhue", "Thừa Thiên Huế"),
                            ("quangnam", "Quảng Nam"),
                            ("quangngai", "Quảng Ngãi"),
                            ("binhdinh", "Bình Định"),
                            ("phuyen", "Phú Yên"),
                            ("khanhhoa", "Khánh Hòa"),
                            ("ninhthuan", "Ninh Thuận"),
                            ("binhthuan", "Bình Thuận"),
                            ("lamdong", "Lâm Đồng"),
                            ("tayninh", "Tây Ninh"),
                            ("binhphuoc", "Bình Phước"),
                            ("longan", "Long An"),
                            ("tiengiang", "Tiền Giang"),
                            ("bentre", "Bến Tre"),
                            ("travinh", "Trà Vinh"),
                            ("vinhlong", "Vĩnh Long"),
                            ("dongthap", "Đồng Tháp"),
                            ("angiang", "An Giang"),
                            ("kiengiang", "Kiên Giang"),
                            ("camau", "Cà Mau"),
                            ("baclieu", "Bạc Liêu"),
                            ("soctrang", "Sóc Trăng"),
                            ("other", "Tỉnh/Thành phố khác"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, upload_to=profiles.models.user_profile_path
                    ),
                ),
                ("preferences", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "student_profiles",
            },
        ),
        migrations.CreateModel(
            name="TutorAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TutorProfile",
            fields=[
                ("education", models.CharField(blank=True, max_length=200)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hanoi", "Hà Nội"),
                            ("hochiminh", "TP. Hồ Chí Minh"),
                            ("danang", "Đà Nẵng"),
                            ("haiphong", "Hải Phòng"),
                            ("cantho", "Cần Thơ"),
                            ("binhduong", "Bình Dương"),
                            ("dongnai", "Đồng Nai"),
                            ("baivungtau", "Bà Rịa - Vũng Tàu"),
                            ("quangninh", "Quảng Ninh"),
                            ("thainguyen", "Thái Nguyên"),
                            ("vinhphuc", "Vĩnh Phúc"),
                            ("bacninh", "Bắc Ninh"),
                            ("haiduong", "Hải Dương"),
                            ("hungyen", "Hưng Yên"),
                            ("namdinh", "Nam Định"),
                            ("thaibinh", "Thái Bình"),
                            ("ninhbinh", "Ninh Bình"),
                            ("thanhhoa", "Thanh Hóa"),
                            ("nghean", "Nghệ An"),
                            ("hatinh", "Hà Tĩnh"),
                            ("quangbinh", "Quảng Bình"),
                            ("quangtri", "Quảng Trị"),
                            ("thuathienhue", "Thừa Thiên Huế"),
                            ("quangnam", "Quảng Nam"),
                            ("quangngai", "Quảng Ngãi"),
                            ("binhdinh", "Bình Định"),
                            ("phuyen", "Phú Yên"),
                            ("khanhhoa", "Khánh Hòa"),
                            ("ninhthuan", "Ninh Thuận"),
                            ("binhthuan", "Bình Thuận"),
                            ("lamdong", "Lâm Đồng"),
                            ("tayninh", "Tây Ninh"),
                            ("binhphuoc", "Bình Phước"),
                            ("longan", "Long An"),
                            ("tiengiang", "Tiền Giang"),
                            ("bentre", "Bến Tre"),
                            ("travinh", "Trà Vinh"),
                            ("vinhlong", "Vĩnh Long"),
                            ("dongthap", "Đồng Tháp"),
                            ("angiang", "An Giang"),
                            ("kiengiang", "Kiên Giang"),
                            ("camau", "Cà Mau"),
                            ("baclieu", "Bạc Liêu"),
                            ("soctrang", "Sóc Trăng"),
                            ("other", "Tỉnh/Thành phố khác"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "rating_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.IntegerField(default=0)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, upload_to=profiles.models.user_profile_path
                    ),
                ),
                ("availability", models.JSONField(blank=True, default=dict)),
                (
                    "price_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "achievements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tutors",
                        to="profiles.tutorachievement",
                    ),
                ),
                (
                    "class_levels",
                    models.ManyToManyField(
                        blank=True, related_name="tutors", to="profiles.classlevel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("basic", "Basic"), ("advanced", "Advanced")],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.subject",
                    ),
                ),
                (
                    "tutor_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_subjects",
                        to="profiles.tutorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorSubjectTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tag", models.CharField(max_length=100)),
                ("is_admin_tag", models.BooleanField(default=False)),
                (
                    "tutor_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="profiles.tutorsubject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="subjects",
            field=models.ManyToManyField(
                through="profiles.TutorSubject", to="subjects.subject"
            ),
        ),
    ]
