# Generated by Django 4.2.7 on 2025-12-15 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="preferred_subjects",
            field=models.ManyToManyField(blank=True, to="subjects.subject"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tutorsubjecttag",
            unique_together={("tutor_subject", "tag")},
        ),
        migrations.AlterUniqueTogether(
            name="tutorsubject",
            unique_together={("tutor_profile", "subject")},
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["price_min"], name="profiles_tu_price_m_ae663f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["price_max"], name="profiles_tu_price_m_328bb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["location"], name="profiles_tu_locatio_05e1bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutorprofile",
            index=models.Index(
                fields=["rating_average"], name="profiles_tu_rating__85bb26_idx"
            ),
        ),
    ]
