# Generated by Django 4.2.7 on 2025-12-14 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorview",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewed_tutors",
                to="profiles.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="tutorview",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="profiles.tutorprofile",
            ),
        ),
        migrations.AddField(
            model_name="tutorsave",
            name="student",
            field=models.ForeignKey(
                db_column="student_profile_uuid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_tutors",
                to="profiles.studentprofile",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="tutorsave",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saves",
                to="profiles.tutorprofile",
            ),
        ),
        migrations.AddField(
            model_name="tutorlike",
            name="student",
            field=models.ForeignKey(
                db_column="student_profile_uuid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_tutors",
                to="profiles.studentprofile",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="tutorlike",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="profiles.tutorprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tutorsave",
            unique_together={("student", "tutor")},
        ),
        migrations.AlterUniqueTogether(
            name="tutorlike",
            unique_together={("student", "tutor")},
        ),
    ]
